# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ADC_Controller_DAC/xem7010.xdc

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/c_addsub_2/c_addsub_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_2 || ORIG_REF_NAME==c_addsub_2} -quiet] -quiet

# IP: C:/Users/Chris/Desktop/test3_0_DAC_cpu_180617_ok/DAC/DAC.srcs/sources_1/ip/on_time_counter/on_time_counter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==on_time_counter || ORIG_REF_NAME==on_time_counter} -quiet] -quiet
